# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: robotology/gh-action-nightly-merge@v1.2.0
        with:
          # Name of the stable branch
          stable_branch: master
          # Name of the development branch
          development_branch: gh-pages
          push_token: ${{ secrets.GITHUB_TOKEN }}

